name = "art-storefront"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "art-storefront-db"
database_id = "5bb1bc6b-f6c1-4ec4-94e5-99bbcc5d175b"
migrations_dir = "db/migrations"
